# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Post.delete_all
Organizer.delete_all
Attendee.delete_all
User.destroy_all
Event.destroy_all


user1 = User.create!(name:"ruby girl", email:"rubyrubyruby84@gmail.com", number:"404356788", password:"rubygirl")
user2 = User.create!(name:"java girl", email:"ilovecoding18@gmail.com", number:"222363788", password:"rubygirl01")
user3 = User.create!(name:"python girl", email:"ilovecoding19@gmail.com", number:"7703856788", password:"rubygirl02")
user4 = User.create!(name:"ruby boy", email:"ilovecode18@gmail.com", number:"3013856788", password:"rubygirl03")
user5 = User.create!(name:"java boy", email:"coding18@gmail.com", number:"3323856788", password:"rubygirl04")
user6 = User.create!(name:"python boy", email:"ilove18@gmail.com", number:"7173856788", password:"rubygirl05")
user7 = User.create!(name:"php girl", email:"lalala@gmail.com", number:"3383856788", password:"rubygirl06")
user8 = User.create!(name:"nodeJs girl", email:"abcdefg@gmail.com", number:"9193856788", password:"rubygirl07")
user9 = User.create!(name:"cSharp girl", email:"oldmcdonald@gmail.com", number:"8193856788", password:"rubygirl08")
user10 = User.create!(name:"php boy", email:"lovelovelove@gmail.com", number:"5163856788", password:"rubygirl09")
user11 = User.create!(name:"nodeJs boy", email:"codears@gmail.com", number:"2403856788", password:"rubygirl010")
user12 = User.create!(name:"cSharp boy", email:"coderocks@gmail.com", number:"2023856788", password:"rubygirl11")

event1 = Event.create!(title:'Women Who Code',date:"10/01/2018" , details:"Come and network with other women in tech",location:"Ponce City Market", time:'2:00')
event2 = Event.create!(title:'Lunch and Learn with Jamie',date:"02/15/2019",details:"Jamie King, General Assembly WDI instructor talks about stuff", time:'6:00' ,location:"Ponce City Market")
event3 = Event.create!(title:'Ted Talk - GraphicQL',date:"11/11/2018" , details:"Hosted by Guys who knows stuff", location:"Georgia Tech", time:'7:30')
event4 = Event.create!(title:'Ruby MeetUp',date:"9/11/2018" ,details:"Let's talk Ruby", location:"Ponce City Market", time:'5:00')
event5 = Event.create!(title:'General Assembly WDI ALumni Event',date:"11/11/2018" ,details:"COme all WDI Alumni, let's party", location:"Ponce City Market", time:'7:00')
event6 = Event.create!(title:'Hackathon',date:"01/11/2019" ,details:"Let's code" , location:"Ponce City Market", time:'6:30')
event7 = Event.create!(title:'Full Stack Meetup',date:"03/15/2019" ,details:"Let's meet up", location:"Ponce City Market", time:'5:30')
event8 = Event.create!(title:'Men who code',date:"04/11/2019" , details: "Let's code dude", location:"Ponce City Market", time:'7:00')


organizer1 = Organizer.create!(event:event1, user: user1)
organizer2 = Organizer.create!(event:event1, user: user2)
organizer3 = Organizer.create!(event:event3, user: user3)
organizer4 = Organizer.create!(event:event3, user: user4)
organizer5 = Organizer.create!(event:event4, user: user5)
organizer6 = Organizer.create!(event:event5, user: user6)
organizer7 = Organizer.create!(event:event6, user: user7)
organizer8 = Organizer.create!(event:event7, user: user8)
organizer9 = Organizer.create!(event:event8, user: user9)
organizer10 = Organizer.create!(event:event2, user: user9)

attendee1 = Attendee.create!(event:event2, user:user4)
attendee2 = Attendee.create!(event:event2, user:user2)
attendee3 = Attendee.create!(event:event2, user:user8)
attendee4 = Attendee.create!(event:event2, user:user10)
attendee5 = Attendee.create!(event:event2, user:user1)
attendee6 = Attendee.create!(event:event2, user:user3)
attendee7 = Attendee.create!(event:event2, user:user7)

attendee8 = Attendee.create!(event:event3, user:user1)
attendee9 = Attendee.create!(event:event3, user:user5)
attendee10 = Attendee.create!(event:event3, user:user7)
attendee11 = Attendee.create!(event:event3, user:user9)
attendee12 = Attendee.create!(event:event3, user:user11)
attendee13 = Attendee.create!(event:event3, user:user8)
attendee14 = Attendee.create!(event:event3, user:user12)
attendee15 = Attendee.create!(event:event3, user:user2)


attendee16 = Attendee.create!(event:event1, user:user3)
attendee17 = Attendee.create!(event:event1, user:user6)
attendee18 = Attendee.create!(event:event1, user:user7)
attendee19 = Attendee.create!(event:event1, user:user8)
attendee20 = Attendee.create!(event:event1, user:user9)
attendee21 = Attendee.create!(event:event1, user:user10)
attendee22 = Attendee.create!(event:event1, user:user11)
attendee23 = Attendee.create!(event:event1, user:user12)

attendee24 = Attendee.create!(event:event4, user:user4)
attendee25 = Attendee.create!(event:event4, user:user2)
attendee26 = Attendee.create!(event:event4, user:user8)
attendee27 = Attendee.create!(event:event4, user:user10)
attendee28 = Attendee.create!(event:event4, user:user1)
attendee29 = Attendee.create!(event:event4, user:user3)
attendee30 = Attendee.create!(event:event4, user:user7)

attendee31 = Attendee.create!(event:event5, user:user4)
attendee32 = Attendee.create!(event:event5, user:user2)
attendee33 = Attendee.create!(event:event5, user:user8)
attendee34 = Attendee.create!(event:event5, user:user11)
attendee35 = Attendee.create!(event:event5, user:user1)
attendee36 = Attendee.create!(event:event5, user:user3)
attendee37 = Attendee.create!(event:event5, user:user7)

attendee38 = Attendee.create!(event:event6, user:user4)
attendee39 = Attendee.create!(event:event6, user:user5)
attendee40 = Attendee.create!(event:event6, user:user8)
attendee41 = Attendee.create!(event:event6, user:user10)
attendee42 = Attendee.create!(event:event6, user:user11)
attendee43 = Attendee.create!(event:event6, user:user3)
attendee44 = Attendee.create!(event:event6, user:user9)
attendee45 = Attendee.create!(event:event6, user:user7)

attendee46 = Attendee.create!(event:event7, user:user4)
attendee47 = Attendee.create!(event:event7, user:user2)
attendee48 = Attendee.create!(event:event7, user:user8)
attendee49 = Attendee.create!(event:event7, user:user10)
attendee50 = Attendee.create!(event:event7, user:user1)
attendee51 = Attendee.create!(event:event7, user:user3)
attendee52 = Attendee.create!(event:event7, user:user7)

attendee53 = Attendee.create!(event:event8, user:user4)
attendee54 = Attendee.create!(event:event8, user:user2)
attendee55 = Attendee.create!(event:event8, user:user8)
attendee56 = Attendee.create!(event:event8, user:user10)
attendee57 = Attendee.create!(event:event8, user:user1)
attendee58 = Attendee.create!(event:event8, user:user3)
attendee59 = Attendee.create!(event:event8, user:user7)


post51 = Post.create!(title:"Just a heads up..we are running a little behind schedule", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", organizer:organizer1, event: event4)
post51 = Post.create!(title:"Can't wait to see everyone", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", organizer:organizer2, event: event5)
post51 = Post.create!(title:" I hope everyone enjoyed", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", organizer:organizer3, event: event3)
post51 = Post.create!(title:"If you want more events like this one, please let me know", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", organizer:organizer4, event: event1)
post51 = Post.create!(title:"Code Universe is the shiznit", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", organizer:organizer5, event: event6)
post51 = Post.create!(title:"No kids allowed at this event, sorry", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", organizer:organizer6, event: event2)
post51 = Post.create!(title:"Bring a friend", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", organizer:organizer7, event: event7)
post51 = Post.create!(title:"Let's do this again", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", organizer:organizer8, event: event8)
post51 = Post.create!(title:"Coders beware, its raining", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", organizer:organizer9, event: event7)
post51 = Post.create!(title:"The details of this event have changed a bit. Details coming soon!", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", organizer:organizer10, event: event1)

post1 = Post.create!(title:"Awesome Event!", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee1, event: event3)
post2 = Post.create!(title:"Wonderful Speakers", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee2, event: event3)
post3 = Post.create!(title:"I want more!", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee3, event: event3)
post4 = Post.create!(title:"This was cool!", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee4, event: event3)
post5 = Post.create!(title:"Started late but it was good", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee5, event: event1)
post6 = Post.create!(title:"Very Interesting", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee6, event: event1)
post7 = Post.create!(title:"Great event", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee7, event: event2)
post8 = Post.create!(title:"Turned into happy quickly", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee8, event: event1)
post9 = Post.create!(title:"Nice", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee9, event: event2)
post10 = Post.create!(title:"You should have been there", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee10,  event: event2)
post11 = Post.create!(title:"Awesome, Awesome, Awesome", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee11,  event: event2)
post12 = Post.create!(title:"Code rocks", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee12,  event: event2)
post13 = Post.create!(title:"Sort of boring", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee13,  event: event2)
post14 = Post.create!(title:"One guy brought his new born", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee14,  event: event2)
post15 = Post.create!(title:"Next time have more beer", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee15,  event: event1)
post16 = Post.create!(title:"Cool", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee16,  event: event2)
post17 = Post.create!(title:"Way over my head", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee17,  event: event2)
post18 = Post.create!(title:"Met great people", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee18,  event: event2)
post19 = Post.create!(title:"Can't wait until the next one", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee19,  event: event2)
post20 = Post.create!(title:"Very fun", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee20,  event: event2)
post21 = Post.create!(title:"What more could you ask for", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee21,  event: event2)
post22 = Post.create!(title:"Cool atmosphere", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee22,  event: event4)
post23 = Post.create!(title:"Yolo", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee23, event: event4)
post24 = Post.create!(title:"Where's Waldo?", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee24, event: event4)
post25 = Post.create!(title:"I thought you'd never ask", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee25, event: event4)
post26 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee26, event: event4)
post27 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee27, event: event5)
post28 = Post.create!(title:"Awesome, Awesome, Awesome", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee28, event: event5)
post29 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee29, event: event5)
post30 = Post.create!(title:"Next time have more beer", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee30, event: event5)
post31 = Post.create!(title:"Great event",comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee30, event: event5)
post32 = Post.create!(title:"You should have been there", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee31, event: event5)
post33 = Post.create!(title:"Very Interesting", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee32, event: event6)
post34 = Post.create!(title:"Way over my head", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee33, event: event6)
post35 = Post.create!(title:"Great event", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee34, event: event6)
post36 = Post.create!(title:"Met great people", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee35, event: event6)
post37 = Post.create!(title:"I thought you'd never ask", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee36, event: event6)
post38 = Post.create!(title:"Sort of boring", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee37, event: event6)
post39 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee38, event: event7)
post40 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee39, event: event7)
post41 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee40, event: event7)
post42 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee41, event: event7)
post43 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee42, event: event7)
post44 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee43, event: event7)
post45 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee42, event: event8)
post46 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee43, event: event8)
post47 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee44, event: event8)
post48 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee45, event: event8)
post49 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee46, event: event1)
post50 = Post.create!(title:"The rain made me sleepy", comment:"loremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem", attendee:attendee47, event: event2)




